// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class DoggylogPigeonPigeonCodecReader: FlutterStandardReader {
}

private class DoggylogPigeonPigeonCodecWriter: FlutterStandardWriter {
}

private class DoggylogPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DoggylogPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DoggylogPigeonPigeonCodecWriter(data: data)
  }
}

class DoggylogPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DoggylogPigeonPigeonCodec(readerWriter: DoggylogPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CalendarSyncBridge {
  func isAvailable() throws -> Bool
  func syncAll() throws -> String
  func importExisting() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CalendarSyncBridgeSetup {
  static var codec: FlutterStandardMessageCodec { DoggylogPigeonPigeonCodec.shared }
  /// Sets up an instance of `CalendarSyncBridge` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CalendarSyncBridge?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.CalendarSyncBridge.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    let syncAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.CalendarSyncBridge.syncAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncAllChannel.setMessageHandler { _, reply in
        do {
          let result = try api.syncAll()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      syncAllChannel.setMessageHandler(nil)
    }
    let importExistingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.CalendarSyncBridge.importExisting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      importExistingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.importExisting()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      importExistingChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CloudBackupBridge {
  func isAvailable() throws -> Bool
  func backupNow() throws -> String
  func restoreLatest() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CloudBackupBridgeSetup {
  static var codec: FlutterStandardMessageCodec { DoggylogPigeonPigeonCodec.shared }
  /// Sets up an instance of `CloudBackupBridge` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CloudBackupBridge?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.CloudBackupBridge.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    let backupNowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.CloudBackupBridge.backupNow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      backupNowChannel.setMessageHandler { _, reply in
        do {
          let result = try api.backupNow()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      backupNowChannel.setMessageHandler(nil)
    }
    let restoreLatestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.CloudBackupBridge.restoreLatest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restoreLatestChannel.setMessageHandler { _, reply in
        do {
          let result = try api.restoreLatest()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      restoreLatestChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WidgetSnapshotBridge {
  func publishSnapshot(payloadJson: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WidgetSnapshotBridgeSetup {
  static var codec: FlutterStandardMessageCodec { DoggylogPigeonPigeonCodec.shared }
  /// Sets up an instance of `WidgetSnapshotBridge` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WidgetSnapshotBridge?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let publishSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.WidgetSnapshotBridge.publishSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      publishSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadJsonArg = args[0] as! String
        do {
          let result = try api.publishSnapshot(payloadJson: payloadJsonArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      publishSnapshotChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DynamicIslandBridge {
  func isSupported() throws -> Bool
  func updateLiveActivity(payloadJson: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DynamicIslandBridgeSetup {
  static var codec: FlutterStandardMessageCodec { DoggylogPigeonPigeonCodec.shared }
  /// Sets up an instance of `DynamicIslandBridge` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DynamicIslandBridge?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.DynamicIslandBridge.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let updateLiveActivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.DynamicIslandBridge.updateLiveActivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateLiveActivityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadJsonArg = args[0] as! String
        do {
          let result = try api.updateLiveActivity(payloadJson: payloadJsonArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateLiveActivityChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SensorBridge {
  func startSensorStream() throws -> Bool
  func stopSensorStream() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SensorBridgeSetup {
  static var codec: FlutterStandardMessageCodec { DoggylogPigeonPigeonCodec.shared }
  /// Sets up an instance of `SensorBridge` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SensorBridge?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startSensorStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.SensorBridge.startSensorStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSensorStreamChannel.setMessageHandler { _, reply in
        do {
          let result = try api.startSensorStream()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startSensorStreamChannel.setMessageHandler(nil)
    }
    let stopSensorStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doggylog.SensorBridge.stopSensorStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopSensorStreamChannel.setMessageHandler { _, reply in
        do {
          try api.stopSensorStream()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopSensorStreamChannel.setMessageHandler(nil)
    }
  }
}
